version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./back/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-productos:
    build: ./back/products
    image: api-productos:1.0
    container_name: api-productos
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    environment:
      API_KEYS: producto-api-linktic
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  api-inventory:
    build: ./back/inventory
    image: api-inventory:1.0
    container_name: api-inventory
    depends_on:
      - postgres-db
      - api-productos
      - kafka
    ports:
      - "8082:8082"
    environment:
      API_KEYS: inventory-api-linktic
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  nginx:
    build:
      context: ./front
      # dockerfile: ../nginx/Dockerfile
    container_name: nginx-frontend
    ports:
      - "80:80"
    depends_on:
      - api-productos
      - api-inventory
    restart: unless-stopped

volumes:
  postgres-data: